name: firebase_phone_auth_provider
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3
  firebase_auth: ^3.3.12
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
