name: firebase_phone_auth_provider
description: A new Flutter package project.
version: 0.0.4
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.4
  firebase_auth: ^3.3.20
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  

flutter:
